// <auto-generated />
namespace EF6CodeFirstDemo.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class Second : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Second));
        
        string IMigrationMetadata.Id
        {
            get { return "201806211853359_Second"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return Resources.GetString("Source"); }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
